# These are supported funding model platforms

ko_fi: eliasilyz # Cukup masukkan username, bukan URL lengkap
custom: ["https://saweria.co/rein122"] # Gunakan kurung siku dan tanda petik untuk URL custom
