# These are supported funding model platforms

github: Eliasilyz # Username dimasukkan ke dalam kurung siku
ko_fi: eliasilyz # Cukup masukkan username, bukan URL lengkap
custom: ["https://saweria.co/rein122"] # Gunakan kurung siku dan tanda petik untuk URL custom
